query GetContributionsCalendar {
  viewer {
    contributionsCollection {
      contributionCalendar {
        colors
        weeks {
          contributionDays {
            date
            contributionCount
            contributionLevel
          }
        }
        totalContributions
      }
    }
  }
}
