# Get Projects
query GetProjects($limit: Int, $offset: Int) {
  projects(pagination: { limit: $limit, start: $offset }) {
    data {
      id
      attributes {
        title
        description
        cover {
          data {
            attributes {
              url
            }
          }
        }
        skills {
          data {
            attributes {
              text
            }
          }
        }
        link
        githubPage
      }
    }
  }
}

# Get Project Details
query GetProjectDetails($id: ID!) {
  project(id: $id) {
    data {
      id
      attributes {
        cover {
          data {
            attributes {
              url
            }
          }
        }
        title
        description
        content
        link
        githubPage
        skills {
          data {
            id
            attributes {
              text
              slug
            }
          }
        }
      }
    }
  }
}

# Get Skills
query GetSkills($limit: Int, $offset: Int) {
  tags(pagination: { limit: $limit, start: $offset }) {
    data {
      id
      attributes {
        slug
        text
        iconUrl
        proficiency
      }
    }
  }
}
