# Get Project Displays for Home Page
query GetProjectDisplays {
  projects(pagination: { limit: 3 }) {
    data {
      id
      attributes {
        title
        description
        cover {
          data {
            attributes {
              url
            }
          }
        }
        skills {
          data {
            attributes {
              text
            }
          }
        }
        link
        githubPage
      }
    }
  }
}

# Get Skills
query GetSkills($limit: Int, $offset: Int) {
  tags(pagination: { limit: $limit, start: $offset }) {
    data {
      id
      attributes {
        slug
        text
        iconUrl
        proficiency
      }
    }
  }
}
